---
kind: Namespace
apiVersion: v1
metadata:
  name: llm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-server
  namespace: llm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      containers:
        - name: main
          image: quay.io/ramalama/ramalama:0.19
          command:
            - "sh"
            - "-c"
          args:
            - "sleep 100000"
          ports:
            - containerPort: 8000
          resources:
            limits:
              devic.es/dri: 1
---
apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: llm
spec:
  type: ClusterIP
  selector:
    app: llama-server
  ports:
    - port: 8000
      targetPort: 8000